alias my_alias='/path/to/my/file'
alias printPath='python ${HOME}/printPath.py -p $PATH'
alias edzsh='vim ~/.zshrc && source ~/.zshrc'
alias edvim='vim ~/.vimrc'
alias wralias='zsh ~/writeAlias.sh'
alias edalias='vim ~/.zsh/aliases.sh'
alias pve='python3 -m venv .venv && source ./.venv/bin/activate'
alias sve="source ./.venv/bin/activate"
alias rda='yarn create react-app $1 --template redux-typescript'
